import os
import sys
import cv2

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
ROOT_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

from lib.colab_util import *
from lib.options import BaseOptions

# get options
opt = BaseOptions().parse()

class visualization:

    @staticmethod
    def obj_to_video(obj_path, video_path):
        if not os.path.isfile(opt.obj_path):
            raise Exception("obj file does not exist.")
        renderer = set_renderer()
        generate_video_from_obj(obj_path, video_path, renderer)

        # # we cannot play a mp4 video generated by cv2
        # !ffmpeg -i $video_path -vcodec libx264 $video_display_path -y -loglevel quiet
        # video(video_display_path)

    @staticmethod
    def png_to_video(png_folder_path, video_name="output.mp4"):
        png_paths = glob.glob(os.path.join(png_folder_path, '*.png'))
        img_array = []
        for png_path in png_paths:
            img = cv2.imread(png_path)
            height, width, layers = img.shape
            size = (width, height)
            img_array.append(img)

        out = cv2.VideoWriter(video_name, cv2.VideoWriter_fourcc(*'mp4v'), 20.0, size)

        for img in img_array:
            out.write(img)

        out.release()


if __name__ == '__main__':
    visualization.obj_to_video(opt.obj_path, opt.video_path)
